name: Build and Deploy VuePress Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify the node version you want

    - name: Install dependencies
      run: |
        cd docs
        npm install

    - name: Build VuePress site
      run: |
        cd docs
        npm run docs:build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
